//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NM_Velo_LACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> DateDeNaissance { get; set; }
        public string MotDePasse { get; set; }
    }
}
