// <auto-generated />
namespace NM_Velo_LACS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BD_Velo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BD_Velo));
        
        string IMigrationMetadata.Id
        {
            get { return "202012172018257_BD_Velo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
